FROM --platform=linux/arm64 public.ecr.aws/lambda/python:3.12-arm64

RUN yum install -y gcc python3-dev && \
    yum clean all

COPY . ${LAMBDA_TASK_ROOT}/

RUN cd ${LAMBDA_TASK_ROOT} && \
    python -m pip install poetry==1.8.3 && \
    poetry export -f requirements.txt --without-hashes > requirements.txt && \
    python -m pip install -r requirements.txt
